[package]
name = "airmash-server"
version = "0.1.0"
authors = ["STEAMROLLER"]

[profile.release]
debug = true
lto = true

[dependencies]
simple_logger = "*"
log = "0.4.1"
specs = "*"
specs-derive = "*"
dimensioned = "*"
lazy_static = "*"
fnv = "*"
rand = "*"
shred = { version="*", features=["nightly"] }
shred-derive = "*"
shrev = "*"
tokio = "*"
tokio-core = "*"

[dependencies.uuid]
version = "*"
features=["v5"]

[dependencies.websocket]
version = "*"
default-features = false
features = [ "async", "async-ssl" ]

[dependencies.airmash-protocol]
git = "https://github.com/steamroller-airmash/airmash-protocol-rs"
branch = "dev"
features = [ "specs" ]
