
[profile.release]
# Turn on nice backtraces even when in release mode
debug = true
#lto = true

[workspace]
members = [
	"server",
	"base",
	"ctf",
	"ffa",
	"specgen",
	"bounded-queue",
	"special-map"
]
