[package]
name = "airmash-server"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"

[features]
# If enabled, set TCP_NODELAY on incoming connections
nodelay = []
# Enable using the client's IP to determine
# a default flag if they don't provide one.
geoip = [ "geolocate-ip" ]
# Enable looking for the X-Forwarded-For header
# when determining client IP address
proxied = []
# Turn on bot blocking settings
block-bots = []

[build-dependencies]
specgen = { path = "../specgen" }

[dependencies]
simple_logger = "*"
log = "0.4.1"
specs = "*"
specs-derive = "*"
dimensioned = "*"
lazy_static = "*"
fnv = "*"
rand = "*"
shred = "*"
shred-derive = "*"
shrev = "*"
tokio = "*"
tokio-core = "*"
rayon = "1.0"
htmlescape = "*"
hibitset = "*"
bounded-queue = { path = "../bounded-queue" }

[dependencies.cadence]
version = "0.14"
#optional = true

[dependencies.uuid]
version = "*"
features=["v5"]

# This and websocket must be versioned together
[dependencies.hyper]
version = "0.10"

[dependencies.websocket]
version = "0.20"
default-features = false
features = [ "async", "async-ssl" ]

[dependencies.geolocate-ip]
git = "https://github.com/phantomical/rust-geolocate-ip"
optional = true
