[package]
name = "airmash-server"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'


[features]
# Have logging on by default, it doesn't do anything
# unless the environment variable is on
default = [ "sentry" ]
# If enabled, set TCP_NODELAY on incoming connections
nodelay = []
# Enable looking for the X-Forwarded-For header
# when determining client IP address
proxied = []
# Turn on bot blocking settings
block-bots = []

[dependencies]
log = "0.4"
specs = { version = "*", features = ["nightly"] }
specs-derive = "*"
dimensioned = "*"
lazy_static = "*"
fnv = "*"
rand = "0.4"
shred = "*"
shred-derive = "*"
shrev = "*"
tokio = "*"
rayon = "1.0"
htmlescape = "*"
hibitset = "*"
bounded-queue = { path = "../bounded-queue" }
special-map = { path = "../special-map" }
airmash-protocol-v5 = { git="https://github.com/steamroller-airmash/airmash-protocol-v5"}
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ws = "*"
futures = "*"
hyper = "0.10"
hashbrown = "*"

[dependencies.sentry]
optional = true
version = "*"

[dependencies.airmash-protocol]
version = "0.3"
features = ["specs"]
git = "https://github.com/steamroller-airmash/airmash-protocol-rs"

[dependencies.uuid]
version = "*"
features=["v5"]
