[package]
name = "airmash-server"
version = "0.1.0"
authors = ["STEAMROLLER"]

[features]
nodelay = []
geoip = [ "geolocate-ip" ]

[profile.release]
debug = true
lto = true

[build-dependencies]
phf_codegen = "^0.7"
specgen = { path = "../specgen" }

[dependencies]
simple_logger = "*"
log = "0.4.1"
specs = "*"
specs-derive = "*"
dimensioned = "*"
lazy_static = "*"
fnv = "*"
rand = "*"
shred = { version="*", features=["nightly"] }
shred-derive = "*"
shrev = "*"
tokio = "*"
tokio-core = "*"
rayon = "*"
phf = "*"
bit_field = "*"
htmlescape = "*"

[dependencies.ctrlc]
version = "*"
features = [ "termination" ]

[dependencies.uuid]
version = "*"
features=["v5"]

[dependencies.websocket]
version = "*"
default-features = false
features = [ "async", "async-ssl" ]

[dependencies.geolocate-ip]
git = "https://github.com/phantomical/rust-geolocate-ip"
optional = true
