[package]
name = "airmash-server-ctf"
version = "0.1.0"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"

[dependencies]
specs = "*"
shrev = "*"
shred = "*"
fnv = "*"
log = "0.4"
rand = "*"
specs-derive = "*"
shred-derive = "*"
lazy_static = "*"
htmlescape = "*"
simple_logger = "*"

[dependencies.airmash-server]
path = '../server'
# Enable GeoIP based default flags
# Enable looking for X-Forwarded-For within the request
features = [ "geoip", "proxied" ]
