[package]
name = "airmash-server-ffa"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
description = "Airmash CTF game mode"
publish = false
repository = 'https://github.com/steamroller-airmash/airmash-server'


[dependencies]
specs = "*"
shred = "*"
specs-derive = "*"
shred-derive = "*"
airmash-server = { path='../server' }
log = "*"
env_logger = "*"
rand = "0.4"
lazy_static = "*"
