[package]
name = "protocol-common"
version = "0.0.1"
authors = ["STEAMROLLER"]
publish = false

[features]

[dependencies]
specs = "*"
lazy_static = "*"
fnv = "*"
dimensioned = "*"

[dependencies.serde]
version = "*"
features = ["derive"]
optional = true
