[package]
name = "base"
version = "0.0.1"
authors = ["STEAMROLLER"]
license = "Apache-2.0 OR MIT"
description = "Minimal airmash server game mode"

[dependencies]
specs = "*"
airmash-server = { path='../server' }
log = "0.4"
simple_logger = "*"
